### ISSUE TITLE
add SA1 names and borders

### ISSUE THREAD

**Issue by mohsenmailbox** [CxSci/SA-dashboard#17]
Each SA2 covers a number of SA1s,
we would like to show the following after any SA2 is chosen on the dashboard
- names of SA1s covered by that particular SA2 in the sidebar
- SA1 borders inside that particular SA2 with a light color

**Comment by justinanderson** [comment]
Names won't be too hard, but borders will take some work. There's a way to get halfway there with Mapbox's hosted service, but that costs money. It's possible to do borders entirely on our own server, but it will require a fair bit of preprocessing since raw SA1 borders are too much data to send to browsers. We'd need to simplify them and also split them up by SA2.

**Comment by mohsenmailbox** [comment]
Justin, yes, I agree let's leave the borders for later, also there is a text box
"Select a community to learn more about opportunity in that area."
the text box covers the sidebar
While keeping the textbox in the page, we need to change sidebar structure in a way that this problem does not happen

**Comment by mohsenmailbox** [comment]
The sidebar shows the SA1 codes not names.
Justin could you please check for that?

**Comment by justinanderson** [comment]
That's right. SA1s don't have names, just codes. See https://www.abs.gov.au/ausstats/abs@.nsf/Lookup/by%20Subject/1270.0.55.001~July%202016~Main%20Features~Statistical%20Area%20Level%201%20(SA1)~10013.

> SA1s are not named. They are identified either by an 11-digit fully hierarchical code, or by a truncated 7-digit code comprising the State and Territory, SA2 and SA1 identifiers.

**Comment by justinanderson** [comment]
SA1s don't have names and adding their borders is out of scope. We can open a new issue if that becomes a thing again.
