### ISSUE TITLE
overlapping paths

### ISSUE THREAD

**Issue by mohsen-bahrami** [CxSci/SA-dashboard#27]
the paths for outflow, inflow, bi-directional in some cases cover each other completely
for example SA2 named BELAIR

**Comment by justinanderson** [comment]
What if we make them arcs rather than straight lines? They'll likely still intersect at times but shouldn't overlap completely as their curvatures should all differ.

Mapbox GL has [sample code](https://docs.mapbox.com/mapbox-gl-js/example/animate-point-along-route/) for making a line into an arc and animating along it.

**Comment by mohsenmailbox** [comment]
totally agree,
this is the way to solve as I can see in many other websites

**Comment by justinanderson** [comment]
@annika608 Mapbox GL JS displays GeoJSON, and GeoJSON doesn't have a curve primitive, but you can approximate one using LineString.

`redrawBridges()` at https://github.com/CxSci/SA-dashboard/blob/master/src/components/map.js#L265-L601 is what currently draws the lines between selected regions and what animates things moving along them. In particular, the code for drawing routes at https://github.com/CxSci/SA-dashboard/blob/master/src/components/map.js#L444-L502 uses `turf.greatCircle()` to create curved lines between regions. Great circles are the shortest paths on a globe so they're an easy way to get curved lines over long distances, but they're effectively straight within small regions like South Australia.

Someone in the Turf project's issues provided some [sample code](https://github.com/Turfjs/turf/issues/1218#issuecomment-592421977) which appears to do what we're looking for. They do some fanciness to make it possible to use `turf.lineArc()` to draw a curve between two points.

The other wrinkle to this issue is to try to come up with a heuristic for drawing curves where curves to different regions from the same origin are unlikely to overlap each other, as that's the original complaint that lead to this issue.

**Comment by justinanderson** [comment]
We ended up not displaying flows between regions.
